index:
    path: /
    controller: App\Controller\DefaultController::index

property_container_index:
    path: /property_container/index
    controller: App\Controller\PropertyContainerController::index

delegation_index:
    path: /delegation/index
    controller: App\Controller\DelegationController::index