index:
    path: /
    controller: App\Controller\DefaultController::index

property_container_index:
    path: /property_container/index
    controller: App\Controller\PropertyContainerController::index

delegation_index:
    path: /delegation/index
    controller: App\Controller\DelegationController::index

event_channel:
    path: /event_channel/index
    controller: App\Controller\EventChannelController::index

abstract_factory:
    path: /abstract_factory/index
    controller: App\Controller\AbstractFactoryController::index

fabric_method:
    path: /fabric_method/index
    controller: App\Controller\FabricMethodController::index

static_factory:
    path: /static_factory/index
    controller: App\Controller\StaticFactoryController::index

simple_factory:
    path: /simple_factory/index
    controller: App\Controller\SimpleFactoryController::index

singleton:
    path: /singleton/index
    controller: App\Controller\SingletonController::index

strategy:
    path: /strategy/index
    controller: App\Controller\StrategyController::index

multitone:
    path: /multitone/index
    controller: App\Controller\MultitoneController::index

builder:
    path: /builder/index
    controller: App\Controller\BuilderController::index

lazy_load:
    path: /lazy_load/index
    controller: App\Controller\LazyLoadController::index
